baseURL = 'https://azadder.com/'
languageCode = 'en-us'
title = 'azadder'
theme = 'beautifulhugo'

[Params]
selfHosted = true
includePhotoswipe = false
includeKatex = false

jqueryVersion = '3.6.1' # Currently supports 3.5.1 & 3.6.1 when selfHosted = true
jqueryIntegrityValue = 'sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA='
# 3.6.1 = sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=
# 3.5.1 = sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj


bootstrapVersion = '3.4.1' # Currently supports 3.3.7 & 3.4.1 when selfHosted = true
bootstrapCssIntegrityValue = 'sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu'
# 3.3.7 = sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u
# 3.4.1 = sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu

bootstrapJsIntegrityValue = 'sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd'
# 3.3.7 = sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa
# 3.4.1 = sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd